### ISSUE TITLE
Work with users who can only control one eye

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/EyeCommander#37]
We should allow the user to not track a specific eye if they can't blink with it.

Ideally this should be dynamic because the client might alternate the eye that they can control

**Comment by willwade** [comment]
Just to clarify - if you have one eye that is fairly closed all the time - the blink detection will trigger. So it might be wise to just ignore an eye that is shut for too long. Its There is a problem with that approach - we end up triggering the switch on opening the eye rather than on it closing which can make it feel laggy.
